2+2
5*4
2^3
6/7
2+3*4/(5+3)*15/2^2+3*4^2
5e4
weight_kg <- 55
weight_kg
2.2*weight_kg
weight_kg <- 57.5
2.2*weight_kg
weight_lb <- 2.2 * weight_kg
weight_kg <- 100
weight_lb
ls()
rm(weight_lb, weight_kg)
ls()
sqrt(144)
help(log)
log(1000)
log(1000, base=10)
log(1000, 10)
sqrt(log(1000, base=10))
sqrt(log(abs(-4*(2550-50)), 10))
library(readr)
library(dplyr)
ydat <- read_csv(file="brauer2007_tidy.csv")
ydat
head(ydat)
tail(ydat)
dim(ydat)
names(ydat)
str(ydat)
summary(ydat)
glimpse(ydat)
library(skimr)
skim(ydat)
ydat$symbol
mean(ydat$expression)
hist(ydat$expression)
sd(ydat$expression)
range(ydat$expression)
ydat %>% filter(bp=="leucine biosynthesis") %>% group_by(nutrient, symbol) %>% summarize(mean=mean(expression), sd=sd(expression), r=cor(rate, expression))
ydat
View(ydat)
class(ydat)
filter(ydat, symbol=="LEU1")
filter(ydat, symbol=="LEU1" | symbol=="ADH2")
filter(ydat, symbol=="LEU1" & rate==0.05)
filter(ydat, symbol=="LEU1" & rate==0.3)
filter(ydat, symbol=="LEU1" & nutrient=="Leucine")
filter(ydat, symbol=="LEU1" & nutrient=="Glucose")
library(ggplot2)
filter(ydat, symbol=="LEU1") %>% ggplot(aes(rate, expression, colour=nutrient)) + geom_line(lwd=1.5)
filter(ydat, bp=="leucine biosynthesis" & nutrient=="Leucine")
quantile(ydat$expression, probs=0.99)
filter(ydat, expression > quantile(ydat$expression, probs=0.99))
View(filter(ydat, expression > quantile(ydat$expression, probs=0.99)))
leudat <- filter(ydat, bp=="leucine biosynthesis" & nutrient=="Leucine")
write_csv(leudat, "leucinedata.csv")
select(ydat, symbol, systematic_name)
select(ydat, -bp, -mf)
nogo <- select(ydat, -bp, -mf)
filter(nogo, symbol=="LEU1" & rate==0.05)
ydat
nogo
mutate(nogo, signal=2^expression)
mutate(nogo, signal=2^expression, sigsr=sqrt(signal))
nogo
library(tidyr)
mutate(nogo, signal=2^expression, sigsr=sqrt(signal)) %>%
  gather(unit, value, expression:sigsr) %>%
  ggplot(aes(value)) + geom_histogram(bins=100) + facet_wrap(~unit, scales="free")
arrange(ydat, symbol)
arrange(ydat, expression)
arrange(ydat, desc(expression))
filter(ydat, bp=="leucine biosynthesis" & nutrient=="Leucine")
arrange(filter(ydat, bp=="leucine biosynthesis" & nutrient=="Leucine"), symbol)
View(arrange(filter(ydat, bp=="leucine biosynthesis" & nutrient=="Leucine"), symbol))
summarize(ydat, mean(expression))
summarize(ydat, meanexp=mean(expression))
summarize(ydat, r=cor(rate, expression))
summarize(ydat, n())
summarize(ydat, n_distinct(symbol))
ydat
group_by(ydat, nutrient)
group_by(ydat, nutrient, rate)
summarize(group_by(ydat, symbol), meanexp=mean(expression))
summarize(group_by(ydat, nutrient), r=cor(rate, expression))
tail(ydat, 5)
ydat %>% tail(5)
filter(ydat, nutrient=="Leucine")
ydat %>% filter(nutrient=="Leucine")
ydat %>% filter(bp=="leucine biosynthesis") %>% group_by(nutrient) %>% summarize(r=cor(rate, expression)) %>% mutate(r=round(r,2)) %>% arrange(r)
ydat %>% filter(symbol=="ADH2" & rate==0.05) %>% select(nutrient, expression)
ydat %>% filter(rate==0.05 & nutrient=="Glucose") %>% arrange(desc(expression)) %>% head(4)
ydat %>% filter(rate==0.05 & nutrient=="Glucose") %>% arrange(desc(expression)) %>% head(4) %>% select(symbol, expression, bp, mf)
ydat %>% filter(rate==0.05 & bp=="response to stress") %>% group_by(nutrient) %>% summarize(meanexp=mean(expression))
ydat %>% filter(rate==0.05 & bp=="protein biosynthesis") %>% group_by(nutrient) %>% summarize(meanexp=mean(expression))
ydat %>% summarize(n_distinct(mf))
ydat %>% group_by(bp) %>% summarize(n=n_distinct(bp)) %>% arrange(desc(n)) %>% head(10)
ydat %>% group_by(bp) %>% summarize(n=n_distinct(symbol)) %>% arrange(desc(n)) %>% head(10)
ydat %>% group_by(mf) %>% summarize(n=n_distinct(symbol)) %>% arrange(desc(n)) %>% head(10)
ydat %>% filter(bp!="biological process unknown" & mf=="molecular function unknown") %>% select(symbol, bp, mf) %>% distinct()
ydat %>% filter(rate==0.05 & nutrient=="Glucose") %>% group_by(bp) %>% summarize(meanexp=mean(expression)) %>% mutate(meanexp=round(meanexp, 2)) %>% arrange(desc(meanexp))
ydat %>% filter(rate==0.05) %>% group_by(nutrient, bp) %>% summarize(meanexp=mean(expression)) %>% arrange(desc(meanexp)) %>% View()
ydat %>% filter(rate==0.05) %>% group_by(nutrient, bp) %>% summarize(meanexp=mean(expression)) %>% arrange(desc(meanexp)) %>% filter(row_number() <=3)
ydat %>% group_by(nutrient, bp) %>% summarize(r=cor(rate, expression), ngenes=n_distinct(symbol))
ydat %>% group_by(nutrient, bp) %>% summarize(r=cor(rate, expression), ngenes=n_distinct(symbol)) %>% filter(ngenes>=5) %>% mutate(absr=abs(r)) %>% arrange(desc(absr)) %>% filter(row_number()==1)
gm <- read_csv("gapminder.csv")
class(gm)
glimpse(gm)
gm %>% mutate(gdp=gdpPercap*pop) %>% filter(continent=="Asia") %>% group_by(year) %>% summarize(mean(lifeExp), mean(gdp))
ggplot(gm, aes(x = gdpPercap, y = lifeExp))
ggplot(gm, aes(x = gdpPercap, y = lifeExp)) + geom_point()
p <- ggplot(gm, aes(gdpPercap, lifeExp))
p
p + geom_point()
p + geom_point() + scale_x_log10()
p <- p + scale_x_log10()
p
p + geom_point()
p + geom_point(aes(color=continent))
p + geom_point(color="blue", pch=17, size=8, alpha=1/4)
p + geom_point(aes(col=continent, shape=continent, size=lifeExp))
p + geom_point(aes(col=continent), size=3)
ggplot(gm, aes(x = gdpPercap, y = lifeExp)) + scale_x_log10() + geom_point(aes(color=continent), size=2) 
p + geom_point() + geom_smooth()
p + geom_point() + geom_smooth(lwd=2, se=FALSE, method="lm", col="red")
p + geom_point(aes(color = continent)) + geom_smooth()
p + aes(color = continent) + geom_point() + geom_smooth()
p + aes(color = continent) + geom_point() + geom_smooth(se=F, lwd=2)
p + geom_point() + facet_wrap(~continent)
p + geom_point() + geom_smooth() + facet_wrap(~continent, ncol=1)
p + geom_point()
ggsave(file="myplot.png")
pfinal <- p + geom_point() + geom_smooth() + facet_wrap(~continent, ncol=1)
ggsave(pfinal, file="myplot.pdf", width=5, height=15)
pex1 <- ggplot(gm, aes(x = year, y = lifeExp)) + geom_point() + geom_smooth(se=T) + facet_wrap(~continent)
pex1
pex1b <- ggplot(gm %>% filter(continent!="Oceania"), aes(year, lifeExp)) + geom_line(aes(group=country), alpha=0.5) + geom_smooth(se=F, lwd=3) + facet_wrap(~continent)
pex1b
p <- ggplot(gm, aes(continent, lifeExp))
p + geom_point()
p + geom_point(alpha=1/4)
p + geom_jitter()
p + geom_jitter(alpha=1/2)
p + geom_jitter() + geom_boxplot()
p + geom_boxplot(outlier.colour = "red") + geom_jitter(alpha=1/2)
p + geom_violin()
p + geom_violin() + geom_jitter(alpha=1/2)
p + geom_boxplot()
p <- ggplot(gm, aes(x=reorder(continent, lifeExp), y=lifeExp))
p + geom_boxplot()
gm
p <- ggplot(gm, aes(x=reorder(continent, gdpPercap, FUN = function(x) mean(log10(x))), y=gdpPercap)) + scale_y_log10() 
p + geom_boxplot(outlier.colour = "red") + geom_jitter(alpha=1/2)
p <- ggplot(gm, aes(lifeExp))
p + geom_histogram()
p + geom_histogram(bins=30)
p + geom_histogram(bins=10)
p + geom_histogram(bins=200)
p + geom_histogram(bins=60)
p + geom_density()
p + geom_histogram(aes(color=continent))
p + geom_histogram(aes(fill=continent), position="identity")
p + geom_histogram(aes(fill=continent), position="identity", alpha=1/3)
p + geom_density(aes(color=continent))
p + geom_density(aes(fill=continent), alpha=1/4)
p <- ggplot(gm, aes(gdpPercap)) + geom_histogram() + scale_x_log10()
p <- ggplot(gm, aes(gdpPercap)) + geom_density(aes(fill=continent, alpha=1/4)) + scale_x_log10()
p <- ggplot(gm, aes(gdpPercap)) + geom_histogram(aes(fill=continent)) + scale_x_log10() + facet_wrap(~continent, ncol=1)
ggsave(p, file="gdpHist.pdf", width=6, height=10)
p <- ggplot(gm, aes(gdpPercap, lifeExp))
p <- p + scale_x_log10()
p <- p + aes(col=continent) + geom_point() + geom_smooth(lwd=2, se=FALSE)
p <- p + ggtitle("Life expentancy vs GDP by Continent")
p <- p + xlab("GDP Per Capita (USD)") + ylab("Life Expectancy (years)")
p + theme_gray()
p + theme_bw()
p + theme_classic()
